### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by wuuster** [triceam/LowLatencyAudio#1]
How do you use this in your HTML. It's not clear.
thanks

**Comment by triceam** [comment]
The API mehtods are described in the readme file at: https://github.com/triceam/LowLatencyAudio/blob/master/README.md 

Again, you can see a sample app using this plugin at: https://github.com/triceam/Instant-Halloween

More detail describing usage at: http://www.tricedesigns.com/2012/01/25/low-latency-polyphonic-audio-in-phonegap/
